[2025-04-17 17:51:26] [INFO] Showing last 100 lines of logs for bot...
bot-1  | Traceback (most recent call last):
bot-1  |   File "/app/clients/telegram-bot/main.py", line 5, in <module>
bot-1  |     from bot import bot_client
bot-1  |   File "/app/clients/telegram-bot/bot.py", line 5, in <module>
bot-1  |     from agrobot.config import settings
bot-1  | ModuleNotFoundError: No module named 'agrobot'
bot-1  | Traceback (most recent call last):
bot-1  |   File "/app/clients/telegram-bot/main.py", line 5, in <module>
bot-1  |     from bot import bot_client
bot-1  |   File "/app/clients/telegram-bot/bot.py", line 5, in <module>
bot-1  |     from agrobot.config import settings
bot-1  | ModuleNotFoundError: No module named 'agrobot'
bot-1  | Traceback (most recent call last):
bot-1  |   File "/app/clients/telegram-bot/main.py", line 5, in <module>
bot-1  |     from bot import bot_client
bot-1  |   File "/app/clients/telegram-bot/bot.py", line 5, in <module>
bot-1  |     from agrobot.config import settings
bot-1  | ModuleNotFoundError: No module named 'agrobot'
bot-1  | Traceback (most recent call last):
bot-1  |   File "/app/clients/telegram-bot/main.py", line 5, in <module>
bot-1  |     from bot import bot_client
bot-1  |   File "/app/clients/telegram-bot/bot.py", line 5, in <module>
bot-1  |     from agrobot.config import settings
bot-1  | ModuleNotFoundError: No module named 'agrobot'
bot-1  | Traceback (most recent call last):
bot-1  |   File "/app/clients/telegram-bot/main.py", line 5, in <module>
bot-1  |     from bot import bot_client
bot-1  |   File "/app/clients/telegram-bot/bot.py", line 5, in <module>
bot-1  |     from agrobot.config import settings
bot-1  | ModuleNotFoundError: No module named 'agrobot'
bot-1  | Traceback (most recent call last):
bot-1  |   File "/app/clients/telegram-bot/main.py", line 5, in <module>
bot-1  |     from bot import bot_client
bot-1  |   File "/app/clients/telegram-bot/bot.py", line 5, in <module>
bot-1  |     from agrobot.config import settings
bot-1  | ModuleNotFoundError: No module named 'agrobot'
bot-1  | Traceback (most recent call last):
bot-1  |   File "/app/clients/telegram-bot/main.py", line 5, in <module>
bot-1  |     from bot import bot_client
bot-1  |   File "/app/clients/telegram-bot/bot.py", line 5, in <module>
bot-1  |     from agrobot.config import settings
bot-1  | ModuleNotFoundError: No module named 'agrobot'
bot-1  | Traceback (most recent call last):
bot-1  |   File "/app/clients/telegram-bot/main.py", line 5, in <module>
bot-1  |     from bot import bot_client
bot-1  |   File "/app/clients/telegram-bot/bot.py", line 5, in <module>
bot-1  |     from agrobot.config import settings
bot-1  | ModuleNotFoundError: No module named 'agrobot'
bot-1  | Traceback (most recent call last):
bot-1  |   File "/app/clients/telegram-bot/main.py", line 5, in <module>
bot-1  |     from bot import bot_client
bot-1  |   File "/app/clients/telegram-bot/bot.py", line 5, in <module>
bot-1  |     from agrobot.config import settings
bot-1  | ModuleNotFoundError: No module named 'agrobot'
bot-1  | Traceback (most recent call last):
bot-1  |   File "/app/clients/telegram-bot/main.py", line 5, in <module>
bot-1  |     from bot import bot_client
bot-1  |   File "/app/clients/telegram-bot/bot.py", line 5, in <module>
bot-1  |     from agrobot.config import settings
bot-1  | ModuleNotFoundError: No module named 'agrobot'
